### ISSUE TITLE
Some lines in the blocklist have wrong format

### ISSUE THREAD

**Issue by smol-loli** [Naunter/BT_BlockLists#19]
At the day of writing (13.04.2023 10:51 UTC+2) the current blocklist release has wrong formated lines from line 24186 to 24197 and a few other lines (see image) causing error messages in transmission. idk if this is expected or not so i just want to let you know :)

![Screenshot_20230413_105526](https://user-images.githubusercontent.com/118623325/231708244-46b0d877-cd2e-414e-a8ec-39f14f7f4376.png)

**Comment by Naunter** [comment]
The error is cause by the blocklist does not compatible with the new `Transmission v4`. 

Since `Transmission` support IPv6 block list rules, it will read lines with colons. If the line does not match the correct IPv6 structure (e.g. blocklist_de:2001:41d0:203:5c64::-2001:41d0:203:5c64::), it will report an error.

Look at the error line 24186 to 24197, we can see there are 2 colons in the line, "....TCP:443:64....".

![24187-24197](https://user-images.githubusercontent.com/17890335/231943497-0ef12a6d-4d14-4cab-af03-03061f919e45.png)

Same error in line 45451 and others.
![45451](https://user-images.githubusercontent.com/17890335/231943780-396bc8ca-d0b4-4a00-b3df-10add64b927e.png)

The line 536235 is IP range issue, I don't know why...it should within 0-255.
![536235](https://user-images.githubusercontent.com/17890335/231943989-95c6e42d-fd0d-4486-84e6-3ea33fe8bdd0.png)

Line 698952 the SPACE problem, can be ignored.
![698952](https://user-images.githubusercontent.com/17890335/231944027-47fd9461-7b4d-414c-8775-3183a3d876f0.png)

Ok, back to the colons issue, I can use `sed` to remove those duplicated colons. I tried and researched, also asked GPT, the result I got is `sed 's/\(:.*:\)/:/'` . 
![Screenshot_2023-04-14_00-58-25](https://user-images.githubusercontent.com/17890335/231945618-76021c7c-5ef5-4c70-8115-96a3c35b3df5.png)

Great, problem solve. Really? Nope, the above `sed` command will also destroy the IPv6 rules because in a IPv6 address has multiple colons. The `sed` command will remove all the extra colons in a IPv6 line.
For example, `blocklist_de:2001:41d0:203:5c64::-2001:41d0:203:5c64::` will become `blocklist_de:`.

Right now I stuck here...All knowledge of `sed` I learned is returned to my college professor 😂

Anyway, those errors you can just ignore.

**Comment by smol-loli** [comment]
Okay, thank you very much :)
